version: "3.8"

services:

  postgres:
    image: postgres:16

    container_name: employee-postgres

    restart: always

    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sravan.7721

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  employee-app:
    build: .

    container_name: employee-app

    restart: always

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Sravan.7721

volumes:
  postgres_data: